services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  
  sqlserver:
    build:
      context: .
      dockerfile: SQLServer.Dockerfile
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"